
### base url for users
@host_1= http://localhost:8000/api/users
@id=614d70d9815cc69e5c091b74
@BearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGQ3MGQ5ODE1Y2M2OWU1YzA5MWI3NCIsImlhdCI6MTYzMjk3OTk0NywiZXhwIjoxNjM0NzA3OTQ3fQ.6vnjGSRUwH0VhMewEe3aKWu-qo08EHqIixvc_4O9u44

### register user
POST {{host_1}}/register/ HTTP/1.1
Content-Type: application/json

{
    "firstName":"india",
    "lastName":"india",
    "email":"india@gmail.com",
    "password":"india"
}

### Login user
POST {{host_1}}/login HTTP/1.1
Content-Type: application/json

{
    "email":"indianinsdian@gmail.com",
    "password":"123456"
}



### FETCH all users
GET {{host_1}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}


### FETCH one user details by id
GET {{host_1}}/{{id}} HTTP/1.1
Content-Type: application/json


### DELETE  user
DELETE  {{host_1}}/{{id}} HTTP/1.1
Content-Type: application/json



### authorization check for user
GET {{host_1}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}




### profile id
GET {{host_1}}/profile/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}



### update user profile
PUT {{host_1}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{BearerToken}}

{
    "firstName":"india",
    "lastName":"Emelia"
}
### update user password 
PUT {{host_1}}/password HTTP/1.1
content-type: application/json
Authorization: Bearer {{BearerToken}}

{
    "password": "4561212sxsx33"
}