
### base url for users
@host_1= http://localhost:8000/api/users
@id=61501bcb88c72e263f221c5f
@BearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTAxYmNiODhjNzJlMjYzZjIyMWM1ZiIsImlhdCI6MTYzMjcxODIxNSwiZXhwIjoxNjM0NDQ2MjE1fQ.rm-0pOKdBm7FIMHUf3iKCreE_C2IJ9Oou4gwmXQuUJY

### register user
POST {{host_1}}/register/ HTTP/1.1
Content-Type: application/json

{
    "firstName":"india",
    "lastName":"india",
    "email":"india@gmail.com",
    "password":"india"
}

### Login user
POST {{host_1}}/login HTTP/1.1
Content-Type: application/json

{
    "email":"indianinsdian@gmail.com",
    "password":"123456"
}



### FETCH all users
GET {{host_1}}/ HTTP/1.1
Content-Type: application/json


### FETCH one user details by id
GET {{host_1}}/{{id}} HTTP/1.1
Content-Type: application/json


### DELETE  user
DELETE  {{host_1}}/{{id}} HTTP/1.1
Content-Type: application/json



### authorization check for user
GET {{host_1}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}




### profile id
GET {{host_1}}/profile/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}
