
### base url for users
@host_1= http://localhost:8000/api/users
@id=61502aff116a8e11b9fa22e7

### register user
POST {{host_1}}/register/ HTTP/1.1
Content-Type: application/json

{
    "firstName":"indianindian1",
    "lastName":"nonindians1",
    "email":"indianindian1@gmail.com",
    "password":"123456"
}

### Login user
POST {{host_1}}/login HTTP/1.1
Content-Type: application/json

{
    "email":"indianinsdian@gmail.com",
    "password":"123456"
}



### FETCH all users
GET {{host_1}}/ HTTP/1.1
Content-Type: application/json


### FETCH one user details by id
GET {{host_1}}/{{id}} HTTP/1.1
Content-Type: application/json


### DELETE  user
DELETE  {{host_1}}/{{id}} HTTP/1.1
Content-Type: application/json

