
### base url for users
@host_1= http://localhost:8000/api/users
@id=6163de3bf147dc759b1ca5e5
@BearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjNkZTNiZjE0N2RjNzU5YjFjYTVlNSIsImlhdCI6MTYzNDI2ODQ4NCwiZXhwIjoxNjM1OTk2NDg0fQ.N1FIXNHxylBRDDuFJJdJ-5V2bLqBiqakLGl1PHJq-Zc

### register user
POST {{host_1}}/register/ HTTP/1.1
Content-Type: application/json

{
    "firstName":"student",
    "lastName":"student",
    "email":"student@gmail.com",
    "password":"student"
}

### Login user
POST {{host_1}}/login HTTP/1.1
Content-Type: application/json

{
    "email":"student@gmail.com",
    "password":"student"
}



### FETCH all users
GET {{host_1}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}


### FETCH one user details by id
GET {{host_1}}/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

{
    "user.id":"6163d641de27cdeee4c5343a"
}


### DELETE  user
DELETE  {{host_1}}/{{id}} HTTP/1.1
Content-Type: application/json



### authorization check for user
GET {{host_1}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}




### profile id
GET {{host_1}}/profile/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}



### update user profile
PUT {{host_1}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{BearerToken}}

{
    "firstName":"alwaysMaster",
    "lastName":"alwaysMaster"
}
### update user password 
PUT {{host_1}}/password HTTP/1.1
content-type: application/json
Authorization: Bearer {{BearerToken}}

{
    "password": "123456789"
}


### follow by user
PUT {{host_1}}/follow HTTP/1.1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
    "followId":"6163d641de27cdeee4c5343a"
}


### unfollow  user 
PUT {{host_1}}/unfollow HTTP/1.1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
    "unFollowId":"6163d641de27cdeee4c5343a"
}