
### base url for users
@host_1= http://localhost:8000/api/users
@id=615a8d8e58dffa35d3bcabe3
@BearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWE4ZDhlNThkZmZhMzVkM2JjYWJlMyIsImlhdCI6MTYzMzMyNDQ2NiwiZXhwIjoxNjM1MDUyNDY2fQ.df7RuaqfNYDhrFn-51z0jlDT_K0s1W5zirntLnI-6xk

### register user
POST {{host_1}}/register/ HTTP/1.1
Content-Type: application/json

{
    "firstName":"vinay",
    "lastName":"s",
    "email":"vinay@gmail.com",
    "password":"india"
}

### Login user
POST {{host_1}}/login HTTP/1.1
Content-Type: application/json

{
    "email":"vinay@gmail.com",
    "password":"india"
}



### FETCH all users
GET {{host_1}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}


### FETCH one user details by id
GET {{host_1}}/{{id}} HTTP/1.1
Content-Type: application/json


### DELETE  user
DELETE  {{host_1}}/{{id}} HTTP/1.1
Content-Type: application/json



### authorization check for user
GET {{host_1}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}




### profile id
GET {{host_1}}/profile/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{BearerToken}}



### update user profile
PUT {{host_1}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{BearerToken}}

{
    "firstName":"kannada",
    "lastName":"reality"
}
### update user password 
PUT {{host_1}}/password HTTP/1.1
content-type: application/json
Authorization: Bearer {{BearerToken}}

{
    "password": "123456789"
}


### follow by user
PUT {{host_1}}/ HTTP/1.1
Content-Type: application/json
Authorization:Bearer {{BearerToken}}

